# Generated by Django 5.0.8 on 2025-06-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0003_alter_order_store_alter_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
