# Generated by Django 5.0.8 on 2025-06-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0004_client_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_authenticated",
            field=models.BooleanField(default=True),
        ),
    ]
